# Harbor container registry
# Replace CLUSTER_IP with first worker's public IP
expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: harbor-tls
  ingress:
    hosts:
      core: harbor.86.38.238.224.nip.io
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: "0"   # no upload size limit
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"

externalURL: https://harbor.86.38.238.224.nip.io

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      size: 20Gi
    chartmuseum:
      size: 5Gi
    jobservice:
      jobLog:
        size: 1Gi
    database:
      size: 5Gi
    redis:
      size: 1Gi
    trivy:
      size: 5Gi

# Change on first login
harborAdminPassword: "Harbor12345!"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    namespace: monitoring
