apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: platform
  sources:
    - repoURL: https://releases.rancher.com/server-charts/stable
      chart: rancher
      targetRevision: 2.9.0
      helm:
        valueFiles:
          - $values/k8s/platform/rancher/values.yaml
    - repoURL: https://github.com/nimamaghsoodi/verda-platform.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
