apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app-backend
  namespace: demo-app
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: demo-app
      component: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
