apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  description: Application workloads
  sourceRepos:
    - '*'
  destinations:
    - namespace: demo-app
      server: https://kubernetes.default.svc
    - namespace: demo-app-staging
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
